Notes/urls.py
from django.urls import path
from .views import manage_note

app_name= "Notes"
urlpatterns = [
    path('', manage_note, name='add'),

]

Participant/urls.py
from django.urls import path
from .views import participant_detail, remove_participant, add_participant, reactivate_participant
app_name = "participants"
urlpatterns = [

    path('<int:id>/', participant_detail, name='participant_details'),
    #/partcipants/<int:id>
    path('delete/<int:participant_id>',  remove_participant, name='remove_participant'),
    path('reactivate/<int:participant_id>', reactivate_participant, name="reactivate_participant"),
    path('add/', add_participant, name='add_participant'),

    ]
    

SleepingBag/urls.py
from django.urls import path
from .views import swap_sleeping_bag, report_lost_bag, wash_now, update_bag, stock

app_name = "bags"

urlpatterns = [
    path('update_bag/<int:bag_id>/', update_bag, name='update'),
    path('swap_bag/<int:participant_id>/', swap_sleeping_bag, name='swap_bag'),
    path('report_lost_bag/<int:bag_id>/', report_lost_bag, name='report_lost_bag'),
    path('wash_now/<int:bag_id>/', wash_now, name='wash_now'),
    path('stock/<int:location_id>/', stock, name='stock'), 


    ]

WasStraat/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth.views import LoginView
from .views import landing_page, login_user, register_user, logout_user
from django.contrib.auth import views as auth_views
from Employee.views import manageEmployee, dashboard_view, participant_detail





urlpatterns = [
    path('', dashboard_view, name="landing_page"),
    # path('participant/<int:id>/', participant_detail, name='participant_detail'),
    path('participants/', include('Participant.urls', namespace='participants')),
    path('bags/', include('SleepingBag.urls', namespace="bags")),
    path('notes/', include("Notes.urls", namespace="notes")),
    path('location/', include("Location.urls")),
   # path('return_dirty_bag/<int:participant_id>/', views.return_dirty_bag, name='return_dirty_bag'),
    path('admin/', admin.site.urls),
    path('login/', login_user, name="login" ),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
]
    

Notes/models.py
from django.db import models
from Participant.models import Participant
from Employee.models import Employee
# Create your models here.
class Note(models.Model):
    #UserID
    note = models.TextField(max_length=500)
    # automatically the date field when the instance
    # auto_now will update the date everytime the instance is saved (last_time_updated)
    date = models.DateTimeField(auto_now_add=True)
    participant = models.ForeignKey(Participant,on_delete=models.SET_NULL, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True)
    #EmployeeID foreigkey 

    def __str__(self):
        if self.participant:
            return f"Bericht betreffend: {self.participant.full_name} Gemaakt op {self.date}"
        else:
            return "Bericht zonder gebruiker"

        #return  "A note about " + self.participant.full_name + " Created at " + str(self.date)


#notes = Notes.objects.all()

#{{note}} = {{note.str}} = 'A note about .......'
# shell python manage.py shell
# from Notes.models import Note
# NOte(note="helowolrdl")

Notes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Note
from Participant.models import Participant
class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ["note", "participant"]
        # widgets = {
        #     'participant': forms.HiddenInput(),
        # }
    # def __init__(self, hidden=False, *args, **kwargs, ):
    #     super(NoteForm, self).__init__(*args, **kwargs)
    #     if hidden:
    #         HiddenParticipantParticipantHiddenself.fields['participant'].widget = forms.HiddenInput()  # Hide participant field
class NoteFormHiddenParticipant(ModelForm):
    class Meta:
        model = Note
        fields = ["note", "participant"]        
        widgets = {
            'participant': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        participant = kwargs.pop('participant', None)
        super(NoteFormHiddenParticipant, self).__init__(*args, **kwargs)
        if participant:
            self.fields['participant'].initial = participant
        self.fields['participant'].queryset = Participant.objects.filter(id=participant.id) if participant else Participant.objects.none()


   #  def __init__(self,*args, **kwargs):
    #     # Access the location from initial, if it's provided
    #     initial_location = kwargs.get('initial', {}).get('location', None)
    #     super().__init__(*args, **kwargs)

    #     # Filter the queryset based on initial_location
    #     if initial_location:
    #         self.fields['participant'].queryset = Participant.objects.filter(
    #             registered_location=initial_location
    # #         )
# 
# class NoteFormParticipantHidden(ModelForm):
#     class Meta:
#         model = Note
#         fields = [" w 'participant': forms.HiddenInput(),}
            # idgets = {
#          
#     def __init(self, location=None, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         if location:
#              self.fields['participant'].queryset = Participant.objects.filter(
#                 registered_location=location
#             )  # Filter t   'participant': forms.HiddenInput(),
#     #     }
# selflocation, =, location=No)#     # def __init__(skwf, *args, **kwargs):
#         location= kwargs.pop('location', None) 
#         super().__init__(*args, **kwargs)

# #     #     if location:
#     #         # employee = Employee.objects.get(user=user)  
#     #         self.fields['participant'].queryset = Participant.objects.filter(
#     #             registered_location=location
          #   )  # Filter the queryset


# form = NoteForm() note particpant writable
# other_form = NoteForm(disabled=True, initial_va)

Notes/views.py
from django.shortcuts import render
from .models import Note
from Employee.models import Employee
from .forms import NoteForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
# Create your views here.

#class NoteForm(forms.Form): 
#     #textfield doesnt work although i use it in models.py
#     # Field here are input field not model field
#     note = forms.CharField(label= 'The note about the participant', max_length=500)
#     participant = form


#view function
#change name below still to do 
# list and add
@login_required
def manage_note(request):
  
    employee = Employee.objects.get(user=request.user)
    referer = request.META.get('HTTP_REFERER')
    if request.method=='POST':          
        # next_url = request.POST.get('next')
        # request.POST.remove('csrfmiddlewaretoken')
        form = NoteForm(request.POST)
        # print('referrer',referer)
        # print('next url', next_url)
        print("data", form.data)
        if form.is_valid():
            print('is valid')
            note = form.save(commit=False)          
            note.employee = employee
            note.save()
            if referer:
                
                return redirect(referer)
                # HttpResponseRedirect(referer)
        else:
            print('errors', form.errors)


    # filter new_notes to only return notes WITH a participant AND that are from the user location
    new_notes = Note.objects.filter(participant__isnull=False)
    new_notes = new_notes.filter(participant__registered_location= employee.location).order_by('-date')
    
    #reversed list
    # display_notes = list(new_notes)[::-1]
    display_notes= new_notes
    #new_notes= Note.objects.exclude(participant__is_null)True)
    form = NoteForm()
    context = {"new_notes": display_notes, 'form':form}
    return render(request, "index.html", context)


        # Return an 'invalid login' error message.

Notes/templates/Notes/header.html
<header>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'landing_page' %}">
                WasStraat
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'landing_page' %}">
                    Homepage
                </a>
                <a class="navbar-item" href="{% url 'notes:add' %}">
                    Notes
                </a>
                {% if user.is_authenticated %} <a class="navbar-item" href="{% url 'bags:stock' location_id=user.employee.location.id %}">Voorraad</a> {% endif %}
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-light" href="{% url 'logout' %}">
                            Logout
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

Notes/templates/Notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notes</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    {% include "Notes/header.html" %}
    <section class="section">
        <div class="container">
            <h1 class="title">Notes</h1>
            <h2 class="subtitle">Add a New Note</h2>
            <form method="post" action="{% url 'notes:add' %}">
                {% csrf_token %}
                {{form}}
                <div class="control">
                    <button class="button is-link" type="submit">Submit</button>
                </div>
                <!-- terug naar deelnemers knop -->
                
            </form>
            <div class="section">
                <div class="container">
                    <a href="{% url 'landing_page' %}" class="return-button">Terug naar alle deelnemers</a>
                </div>
            </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

            {% load tz %}
            {% get_current_timezone as TIME_ZONE %}
            {% now "Y-m-d" as today_date %}
            
            <h2 class="subtitle">Notities vandaag gemaakt:</h2>
            
            <div class="content notes">
                <ul>
                    {% for note in new_notes %}
                        {% if note.date|date:"Y-m-d" == today_date %}
                            <li class="note-item">
                                <div class="note-content">{{ note.note }}</div>
                                <div class="note-meta">
                                    <span>Betreft: <strong>{{ note.participant.first_name }}</strong></span>
                                    <span>Geschreven door: <strong>{{ note.employee }}</strong></span>
                                    <span>Gemaakt op: <strong>{{ note.date|date:"F d, Y" }}</strong></span>
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            
            <h2 class="subtitle">Eerder gemaakte notities:</h2>
            <div class="content notes">
                <ul>
                    {% for note in new_notes %}
                        {% if note.date|date:"Y-m-d" != today_date %}
                            <li class="note-item">
                                <div class="note-content">{{ note.note }}</div>
                                <div class="note-meta">
                                    <span>Betreft: <strong>{{ note.participant.first_name }}</strong></span>
                                    <span>Geschreven door: <strong>{{ note.employee }}</strong></span>
                                    <span>Gemaakt op: <strong>{{ note.date|date:"F d, Y" }}</strong></span>
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
    
    </section>
</body>
</html>

Notes/templates/Notes/landing_page.html
{% extends 'Notes/base.html' %}
{% load static %}

{% block head %}
<title>Uw Dashboard</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block body %}
{% include "Notes/header.html" %}
<section class="section">
    <div class="container">
        <h1 class="title">Welkom, {{ employee.user.first_name }}!</h1>
        <p class="subtitle">Hier zijn de deelnemers bij uw locatie: {{ employee.location.name }}</p>
        
        <!-- Button to add participant -->
{% if employee.can_manage_participants %}
<div>
    <a href="{% url 'participants:add_participant' %}" class="button is-primary" id="add-participant-button" onclick="checkParticipantLimit(event)">Deelnemer Toevoegen</a>
</div>
{% endif %}

        <!-- <pre>
        {% for bag in unwashed_bags %}
                {{ bag.id }} - {{ bag.linked_participant }}
        {% endfor %}
        </pre>
             -->

        <!-- Sleeping Bags to Wash -->
        <!-- <h2 class="subtitle" style="margin-top: 40px;"><span class="icon"><i class="fas fa-washing-machine"></i></span> Slaapzakken die gewassen moeten worden:</h2>
        <p>Hieronder ziet u een lijst van slaapzakken die gewassen moeten worden. Klik op "Markeer als gewassen" nadat u een slaapzak heeft gewassen.</p>
        <ul>
            {% for bag in unwashed_bags %}
            <li>
                <span style="font-weight: bold;">Slaapzak ID:</span> {{ bag.id }} 
                <p>Deelnemer: 
                    {% if bag.linked_participant %}
                        {{ bag.linked_participant.full_name }}
                    {% else %}
                        Geen deelnemer
                    {% endif %}
                    - Status: 
                    {% if bag.status == 'Good' %}
                        <span class="icon has-text-danger"><i class="fas fa-exclamation-triangle"></i></span>
                    {% elif bag.status == 'Damaged' %}
                        <span class="icon has-text-warning"><i class="fas fa-exclamation-circle"></i></span>
                    {% else %}
                        <span class="icon has-text-info"><i class="fas fa-info-circle"></i></span>
                    {% endif %}
                </p>
                <a href="{% url 'bags:wash_now' bag.id %}" class="button is-medium is-primary" onclick="return confirm('Weet u zeker dat u de slaapzak wilt wassen?');">Wassen</a>
            </li>
            {% endfor %}
        </ul> -->


        <!-- Active Participants -->
        <ul>
            {% if messages %}
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            {% endif%}
        </ul>
        <div class="participants-grid">
            {% for data in participant_data %}
                {% if data.participant.is_active %}
                    <div class="participant-card"> 
                        <a href="{% url 'participants:participant_details' data.participant.id %}">
                            <h3>{{ data.participant.full_name }} - <span style="color:green;">Actief</span></h3>
                            <ul>
                                {% for bag in data.sleeping_bags %}
                                    <li>Slaapzak Status: {{ bag.status }}, Laatst gewassen: {{ bag.last_washing_cycle|date:"Y-m-d" }}</li>
                                {% empty %}
                                    <li>Geen slaapzakken gevonden voor deze deelnemer.</li>
                                {% endfor %}
                            </ul>
                        </a>
                    
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <!-- Inactive Participants -->
        <h2 class="subtitle" style="margin-top: 40px;">Inactieve Deelnemers:</h2>
        <ul class="inactive-list">
            {% for data in participant_data %}
                {% if not data.participant.is_active %}
                    <li>
                        {{ data.participant.full_name }} - <span style="color:gray;">Inactief</span>
                        <a href="{% url 'participants:reactivate_participant' data.participant.id %}" class="button is-small is-info" >Reactivatie </a>
                    </li>

                {% endif %}
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

Notes/templates/Notes/manage_employee.html
{% extends 'base.html' %}

{% block head %}
<title>Manage Employee</title>
{% endblock %}

{% block body %}
{% include "header.html" %}
<section class="section">
    <div class="container">
        <h2>Manage Employee</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Employee</button>
        </form>
    </div>
</section>
{% endblock %}

Notes/templates/Notes/participant_detail.html
{% extends 'Notes/base.html' %}
{% load static %}
{% block body %}
{% include "Notes/header.html" %}

<div class="columns">
    <!-- Cliënt Contact Info -->
    <div class="column is-one-third">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    Cliënt: {{ participant.full_name }}
                </p>
            </header>
            <div class="card-content">
                <div class="content">
                    <strong>Locatie::</strong> {{ participant.registered_location.name }}<br>
                    <strong>Geboortedatum:</strong> {{ participant.date_of_birth|date:"Y-m-d" }}
                </div>
            </div>
        </div>
    </div>

    <!-- Status vd Slaapzakken -->
    <div class="column">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    Slaapzakken
                </p>
            </header>
            <div class="card-content">
                <ul>
                    {% for bag in sleeping_bags %}
                    <form method="POST" action="{% url 'update_bag' bag.id %}">
                        {% csrf_token %}
                        <li>
                            <strong>Slaapzak nummer:</strong> {{ bag.id }},
                            <strong>Status:</strong>
                            <select name="status">
                                {% for choice in status_choices %}
                                <option value="{{ choice.0 }}" {% if bag.status == choice.0 %} selected {% endif %}>{{ choice.1 }}</option>
                            {% endfor %}
                            </select>
                            <button type="submit">Save</button>
                            </form>
                            
                            <strong>Laatst Gewassen:</strong>
                            <span>{{ bag.last_washing_cycle }}</span>
                            <button type="button" class="btn btn-primary wash-now-button" data-bag-id="{{ bag.id }}">Was nu</button>,

                            <strong>Gewassen:</strong>
                            <select name="is_washed">
                                <option value="true" {% if bag.is_washed %}selected{% endif %}>✔ Gewassen</option>
                                <option value="false" {% if not bag.is_washed %}selected{% endif %}>✘ Moet gewassen worden</option>
                            </select>,

                            <strong>Locatie:</strong>
                            <select name="is_in_facility">
                                <option value="true" {% if bag.is_in_facility %}selected{% endif %}>Op locatie</option>
                                <option value="false" {% if not bag.is_in_facility %}selected{% endif %}>Met de gebruiker</option>
                            </select>
                            
                            <!-- Report Lost Button -->
                            <a href="javascript:void(0);" class="btn btn-danger report-lost-button" data-bag-id="{{ bag.id }}">Verloren melden</a>
                        </li>
                    </form>
                    {% empty %}
                    <li>Geen slaapzakken gevonden.</li>
                    {% endfor %}
                </ul>
                <!-- Swap Button -->
                <a href="javascript:void(0);" class="btn btn-primary swap-button" data-participant-id="{{ participant.id }}">Slaapzakken omruilen</a>
            </div>
        </div>
    </div>
<!-- Notities -->
<div class="column is-full">
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                Notities
            </p>
        </header>
        <div class="card-content">
            <div class="content">
                <form method="post" action="{% url 'participant_detail' participant.id %}">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Note</label>
                        <div class="control">
                            <textarea name="note" rows="4" class="textarea">{{ form.note.value }}</textarea>
                        </div>
                    </div>
                    <div class="field">
                        {{ form.participant.as_hidden }} 
                    </div>
                    <div class="control">
                        <button class="button is-link" type="submit">Submit</button>
                    </div>
                </form>

                <h2 class="subtitle">Existing Notes are:</h2>
                <div class="content">
                    <ul>
                        {% for note in new_notes %}
                            <li>{{ note.note }} by: {{ note.employee }} - gemaakt op {{ note.date|date:"F d, Y" }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- terug naar deelnemers knop -->
<div class="section">
    <div class="container">
        <a href="{% url 'landing_page' %}" class="return-button">Terug naar alle deelnemers</a>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
$(document).ready(function() {
    $('.swap-button').click(function() {
        var participantId = $(this).data('participant-id');
        var ajaxUrl = `{% url 'swap_bag' 0 %}`.replace('0', participantId);

        $.ajax({
            url: ajaxUrl,
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                if (response.success) {
                    alert('Ruilen Succesvol!: ' + response.message);
                } else {
                    alert('Ruilen mislukt: ' + response.message);
                }
            },
            error: function(xhr, status, error) {
                alert('Technical error: ' + error);
            }
        });
    });

    $('.report-lost-button').click(function() {
        var bagId = $(this).data('bag-id');
        var ajaxUrl = `{% url 'report_lost_bag' 0 %}`.replace('0', bagId);

        $.ajax({
            url: ajaxUrl,
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                if (response.success) {
                    alert('Melding Succesvol!: ' + response.message);
                    location.reload(); // Refresh the page to reflect changes
                } else {
                    alert('Melding mislukt: ' + response.message);
                }
            },
            error: function(xhr, status, error) {
                alert('Technical error: ' + error);
            }
        });
    });

    // Wash now button
    $('.wash-now-button').click(function() {
        var bagId = $(this).data('bag-id');
        var ajaxUrl = `{% url 'wash_now' 0 %}`.replace('0', bagId);

        $.ajax({
            url: ajaxUrl,
            type: 'POST',
            dataType: 'json',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response) {
                if (response.success) {
                    alert('Wassen Succesvol!: ' + response.message);
                    location.reload(); // Refresh the page to reflect changes
                } else {
                    alert('Wassen mislukt: ' + response.message);
                }
            },
            error: function(xhr, status, error) {
                alert('Technical error: ' + error);
            }
        });
    });
});
</script>
{% endblock %}

<!-- 
$('.return-dirty-button').click(function() {
    var participantId = $(this).data('participant-id');
    var ajaxUrl = `{% url 'return_dirty_bag' 0 %}`.replace('0', participantId);

    $.ajax({
        url: ajaxUrl,
        type: 'GET',
        dataType: 'json',
        success: function(response) {
            if (response.success) {
                alert('Terugbrengen Succesvol!: ' + response.message);
            } else {
                alert('Terugbrengen mislukt: ' + response.message);
            }
        },
        error: function(xhr, status, error) {
            alert('Technical error: ' + error);
        }
    });
}); -->